{ 
  imports = [
    ./autostart/default.nix
    ./autoUpdate/default.nix
    ./bluetooth/default.nix
    ./boot/default.nix
    ./cacReader/default.nix
    ./encryption/default.nix
    ./flakes/default.nix
    ./fonts/default.nix
    ./internationisationProps/default.nix
    ./keymaps/default.nix
    ./networking/default.nix
    ./ncsd/default.nix
    ./pipewire/default.nix
    ./ssh/default.nix
    ./stateVersion/default.nix
    ./steam/default.nix
    ./system76/default.nix
    ./timezone/default.nix
    #./unfree/default.nix
    ./user/default.nix
    ./virtualization/default.nix
    ./xserver/default.nix
    ./emacs/default.nix
    ./slock/default.nix
  ];
}
