{
  imports = [
    ./autostart/default.nix
    ./bluetooth/default.nix
    ./boot/default.nix
    ./cacReader/default.nix
    ./containers/default.nix
    ./encryption/default.nix
    ./flakes/default.nix
    ./fonts/default.nix
    ./internationisationProps/default.nix
    ./keymaps/default.nix
    ./networking/default.nix
    ./pipewire/default.nix
    ./ssh/default.nix
    ./stateVersion/default.nix
    ./steam/default.nix
    ./timezone/default.nix
    ./unfree/default.nix
    ./user/default.nix
    ./virtualization/default.nix
    ./xserver/xserver.nix
  ];
}
